CREATE TABLE post (
	id INTEGER PRIMARY KEY,
	title VARCHAR,
	introduction VARCHAR,
	fulltext VARCHAR
);


INSERT INTO post VALUES (null, 'Mauris bibendum nisl dui. Aliquam.', 'Sed eu porttitor ex. Donec scelerisque lectus eu ultrices faucibus. Maecenas commodo erat at vehicula ultricies. Nullam ut ipsum ut ligula convallis rhoncus at quis arcu. Cras tellus quam, vehicula eget tellus id, sagittis pharetra leo. Integer at pretium magna, at efficitur odio. Curabitur ut tincidunt massa, nec varius sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Donec feugiat ex id facilisis sodales. Quisque sodales vulputate metus a bibendum. Sed pretium bibendum semper. Nunc ac justo eu augue ultricies varius. Aenean porta ut felis eu ultrices. Nulla mi diam, congue vel convallis id, pellentesque in nisl. Nam fringilla nulla erat, a sodales risus hendrerit in. Ut a dapibus dolor. Sed tempus metus felis, a molestie dui tristique et. In hac habitasse platea dictumst. Phasellus vitae risus molestie massa feugiat pharetra. Pellentesque eu pulvinar nisi, eu pretium sem. Morbi vestibulum leo vel metus aliquam tristique at vitae felis. Vivamus id pellentesque quam. Integer aliquet fringilla ex, vel tristique augue gravida nec. Donec placerat vel ipsum non aliquam.

Mauris dui eros, rhoncus nec lacus id, commodo porttitor leo. Curabitur bibendum augue a porta tempor. Suspendisse ac ullamcorper ligula. Nulla sit amet libero est. Ut facilisis tellus orci, non lacinia felis semper id. Vivamus sem risus, vulputate id magna nec, fermentum vestibulum metus. Proin arcu mi, aliquet at viverra nec, tristique in odio.');
INSERT INTO post VALUES (null, 'Suspendisse ac felis non dui.', 'Nunc velit velit, consectetur facilisis nunc nec, commodo convallis est. Vestibulum placerat arcu quis consequat finibus. Vivamus hendrerit, libero vitae gravida condimentum, augue nunc volutpat erat, eget iaculis lorem sem et odio. Sed ultricies eget sem quis auctor. Vestibulum enim dui, semper eu purus sed, semper bibendum nunc. Vestibulum et vehicula odio, eget auctor nibh. Nam risus risus, tincidunt nec mi in, consequat ultricies urna. Cras maximus ultrices quam sit amet bibendum. Curabitur accumsan eu sem a gravida.', 'Ut tellus lacus, sollicitudin ac ex eu, malesuada pharetra purus. Nunc ut urna tortor. Donec venenatis egestas lacus, ut sodales quam consectetur egestas. Vivamus ornare ullamcorper magna quis laoreet. Duis eu vestibulum felis, sit amet sagittis turpis. Donec congue augue sed mi molestie dapibus. Phasellus convallis enim velit. Aliquam erat volutpat. Etiam urna est, volutpat eget libero eget, ultricies suscipit ex. Duis vel erat et libero pharetra faucibus. Vestibulum dictum scelerisque est cursus egestas.

Vivamus facilisis nibh id tellus pharetra pulvinar quis vitae lacus. Aenean rutrum vel arcu consectetur ultricies. Nullam tincidunt pulvinar arcu. Fusce at est odio. Etiam in metus nec felis consequat varius. Aliquam vestibulum a sem et ultrices. In arcu purus, mattis vitae nunc nec, fringilla pellentesque arcu.');
INSERT INTO post VALUES (null, 'Curabitur lobortis hendrerit dui, posuere.', 'Cras laoreet aliquam eleifend. Aenean mollis, neque vitae hendrerit fermentum, erat ex dictum massa, vel venenatis odio nisl vel ante. Mauris porta diam urna, gravida porttitor nulla venenatis eu. Phasellus consectetur ipsum at quam tincidunt eleifend. Donec ornare ultrices lorem, id ultricies nibh vulputate vel. Aliquam condimentum consequat laoreet. Nunc hendrerit ipsum vitae elementum scelerisque. Aliquam erat volutpat. Sed cursus dictum nibh et euismod. Duis ultricies leo id arcu sodales mollis. Ut quam ligula, viverra vitae ante a, gravida aliquet justo. Nulla vel ultricies purus. Ut tincidunt gravida eros. Donec ac eleifend lacus. Integer a quam dictum, fermentum lectus at, volutpat ipsum.', 'Maecenas ut ante purus. Donec varius auctor orci, at tempor nisi vehicula eu. Nulla viverra ligula quis nibh vulputate, et suscipit ex ornare. Nunc dapibus eros risus, nec efficitur odio tincidunt id. Etiam efficitur urna at sapien aliquam cursus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur mollis dolor mauris, vel dictum massa posuere laoreet. Sed et ligula et urna tristique pellentesque. Cras vitae maximus felis, sit amet tristique ante. Mauris consectetur, neque id accumsan tincidunt, risus risus tincidunt nulla, et vehicula tellus tellus at turpis. Sed sit amet sem interdum, malesuada neque quis, sollicitudin augue. Maecenas scelerisque elit at ligula ultrices fringilla. Proin lacinia, justo at luctus interdum, felis urna bibendum lectus, ac gravida est augue sit amet velit.

Maecenas malesuada et dui tempus luctus. Donec malesuada sapien nisl, id eleifend justo maximus id. Etiam nec lorem pharetra, porttitor nulla auctor, dapibus massa. Proin faucibus velit maximus nunc rhoncus, sed volutpat turpis sagittis. Vivamus malesuada sollicitudin velit eget finibus. Nunc mattis sapien sed rhoncus viverra. Nunc blandit varius felis, id egestas lectus elementum at.');
